"""A thin client for the local OpenAI-compatible model server.

Everything this module does is *optional*. The server is a separate process on
the host that may simply not be running, and the whole feature it powers --
narrative summaries of a file's QC and metadata -- is additive: when the server
is down the app behaves exactly as it did before, with nothing new populated and
nothing broken. That single premise is why the failure style here is "return
None and log", never "raise and fail the job".

Uses stdlib urllib rather than httpx because httpx is a dev-only dependency in
this project; the calls are simple JSON POSTs and this runs in a worker thread,
so there is nothing to gain from an async client.
"""

import json
import urllib.error
import urllib.request

from app.config import settings
from app.logging import get_logger

log = get_logger(__name__)


def _post(path: str, body: dict, timeout: float) -> dict | None:
    """POST JSON and return the decoded response, or None on any failure.

    Deliberately catches everything. The caller's contract with the rest of the
    app is "a summary appears when it can", so a malformed response, a closed
    port and a timeout all mean the same thing here and are all non-events.
    """
    url = f"{settings.llm_base_url.rstrip('/')}{path}"
    payload = json.dumps(body).encode()
    request = urllib.request.Request(
        url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as e:
        # Read the body: a 400 from the model server usually explains itself,
        # and that explanation is the whole diagnostic when a prompt is at
        # fault rather than the connection.
        detail = ""
        try:
            detail = e.read().decode()[:500]
        except Exception:  # noqa: BLE001 - diagnostics must not raise
            pass
        log.warning("llm_http_error", url=url, status=e.code, detail=detail)
    except Exception as e:  # noqa: BLE001 - see docstring
        log.info("llm_unavailable", url=url, error=str(e))
    return None


def is_available() -> bool:
    """Whether the model server is up right now.

    Checked immediately before use rather than cached: this is a local process
    the user starts and stops by hand, so a cached "up" from ten minutes ago is
    exactly the answer most likely to be wrong.
    """
    url = f"{settings.llm_base_url.rstrip('/')}/health"
    try:
        with urllib.request.urlopen(url, timeout=settings.llm_health_timeout_seconds) as response:
            if response.status != 200:
                return False
            body = json.loads(response.read().decode())
    except Exception as e:  # noqa: BLE001 - down is a normal state, not an error
        log.info("llm_health_unavailable", url=url, error=str(e))
        return False
    return str(body.get("status", "")).lower() == "ok"


def default_model() -> str | None:
    """The model id to send, preferring configuration over discovery.

    Discovery exists so the feature works with no configuration at all: the
    server reports what it has loaded, and with a single-model server -- which
    is the setup this targets -- that answer is unambiguous.
    """
    if settings.llm_model:
        return settings.llm_model

    url = f"{settings.llm_base_url.rstrip('/')}/v1/models"
    try:
        with urllib.request.urlopen(url, timeout=settings.llm_health_timeout_seconds) as response:
            body = json.loads(response.read().decode())
    except Exception as e:  # noqa: BLE001
        log.info("llm_models_unavailable", url=url, error=str(e))
        return None

    entries = body.get("data") or []
    # Prefer a model the server says is actually resident: asking for one it
    # would have to load from disk turns a few-second call into a slow one.
    for entry in entries:
        if entry.get("loaded") and entry.get("id"):
            return str(entry["id"])
    for entry in entries:
        if entry.get("id"):
            return str(entry["id"])
    return None


def complete(*, system: str, user: str, max_tokens: int | None = None) -> tuple[str, str] | None:
    """Run one chat completion. Returns (text, model_id), or None if unavailable.

    The model id comes back with the text because it is recorded alongside the
    summary: a narrative generated by a model the user has since swapped out is
    worth being able to identify as such.
    """
    model = default_model()
    if model is None:
        return None

    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        # Low but not zero. These summaries restate measured numbers, so
        # invention is the failure mode to suppress; a little variation keeps
        # a re-run from being pointlessly identical.
        "temperature": 0.2,
        "max_tokens": max_tokens or settings.llm_max_tokens,
        "stream": False,
    }

    response = _post("/v1/chat/completions", body, settings.llm_timeout_seconds)
    if response is None:
        return None

    try:
        text = response["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError):
        log.warning("llm_response_unparseable", keys=sorted(response) if response else None)
        return None

    if not isinstance(text, str) or not text.strip():
        return None

    return text.strip(), model
