"""Application settings, loaded from the environment."""

import platform
from functools import lru_cache
from pathlib import Path

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

# DeepVariant ships as a sibling container rather than a binary in our image,
# and no single tag covers both architectures. Google publishes amd64 only; the
# arm64 build is a community port. Neither manifest is multi-arch -- both are
# single-platform, verified 2026-08-01 with `docker manifest inspect -v`:
# google/deepvariant:1.9.0 reports architecture "amd64", and the port reports
# "arm64". So picking the wrong one does not fail at pull time with anything
# that names the cause; it pulls with a platform-mismatch warning and then dies
# at `docker run` with "exec format error" deep inside a job.
_DEEPVARIANT_IMAGE_AMD64 = "google/deepvariant:1.9.0"
_DEEPVARIANT_IMAGE_ARM64 = "ghcr.io/antomicblitz/deepvariant-arm64:v1.9.0-arm64.6"


def is_arm64() -> bool:
    """Whether this machine runs the arm64 DeepVariant port.

    Read at import time for the image default and again when building the
    `docker run` invocation, which needs to know whether the Graviton fastmath
    workaround applies. `platform.machine()` reports the *container's*
    architecture, which is the one that matters: the sibling container the
    daemon starts inherits the host's platform, and the worker container is
    already running on it.
    """
    return platform.machine().lower() in {"aarch64", "arm64"}


def default_deepvariant_image() -> str:
    return _DEEPVARIANT_IMAGE_ARM64 if is_arm64() else _DEEPVARIANT_IMAGE_AMD64


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore", populate_by_name=True)

    # --- Infrastructure ---
    mongo_url: str = "mongodb://mongo:27017/biopipe?replicaSet=rs0&directConnection=true"
    mongo_db: str = "biopipe"
    redis_url: str = "redis://redis:6379/0"

    # --- Storage ---
    bioinfo_home: Path = Path("/data")
    # Colon-separated roots that register-in-place may reference.
    bioinfo_register_roots: str = "/data"
    max_simple_upload_bytes: int = 100 * 1024 * 1024

    # --- Queue ---
    lease_ttl_seconds: int = 30
    worker_max_concurrent: int = 4
    worker_id: str = ""  # defaults to hostname:pid at startup
    worker_node_id: str = "primary"  # stable name for this physical machine
    enrollment_key: str = ""  # shared secret for child-node enrollment (empty = open)
    # Externally-routable hostname for node-connection URLs during remote
    # provisioning. Empty = auto-discover via UDP socket heuristic.
    primary_hostname: str = ""
    primary_api_url: str = ""  # where child nodes reach the primary's API (empty = primary)
    # "primary" (default) or "compute" — controls blob-transfer behaviour.
    node_type: str = "primary"
    # Symmetric secret shared between primary and compute nodes for
    # blob-transfer auth. Generated by the primary; the launcher passes
    # it to the child during setup.
    node_shared_secret: str = ""
    job_max_attempts: int = 5
    # Reaper/promotion cadence.
    reaper_interval_seconds: float = 10.0
    promote_interval_seconds: float = 30.0
    drain_timeout_seconds: float = 60.0

    # --- Load governor (Phase 4; stubbed OPEN until then) ---
    bioinfo_cpu_budget: float | None = None
    bioinfo_mem_budget_mb: int | None = None

    # Kernel-enforced ceiling on the worker container, set by the launcher.
    # None means no hard cap. `api` is not itself capped, so this arrives as
    # an env var rather than being read from a cgroup -- see
    # docs/superpowers/specs/2026-08-07-cgroup-hard-limits-design.md.
    bioflow_hard_mem_mb: int | None = None

    @field_validator("bioflow_hard_mem_mb", mode="before")
    @classmethod
    def _empty_string_hard_mem_mb_is_none(cls, v):
        """Compose always sets BIOFLOW_HARD_MEM_MB, resolving to '' when the
        launcher has not configured a hard limit (the default, off state) --
        pydantic-settings does not treat '' as None for an int field on its
        own, so without this the api container fails to even start whenever
        no hard limit is set, which is the common case.
        """
        if v == "":
            return None
        return v

    # --- Metadata enrichment ---
    # Looks up SRR/SRX accessions at NCBI during ingest. Outbound network call;
    # set false to keep the stack fully offline.
    sra_enrichment_enabled: bool = True

    # Looks up GCA/GCF assembly accessions at NCBI during ingest. Outbound
    # network call; set false to keep the stack fully offline.
    assembly_enrichment_enabled: bool = True

    # --- Pipelines ---
    # Bare names by default, resolved on PATH; override with an absolute path
    # to pin a specific build.
    fastp_path: str = "fastp"
    fastqc_path: str = "fastqc"
    cutadapt_path: str = "cutadapt"
    # Debian ships no bare `trimmomatic`: the package installs TrimmomaticPE
    # and TrimmomaticSE as separate entry points around the JAR. The runner
    # picks between them by read layout (paired vs single-end).
    trimmomatic_path: str = "TrimmomaticSE"  # kept for the version probe only
    trimmomatic_pe_path: str = "TrimmomaticPE"
    trimmomatic_se_path: str = "TrimmomaticSE"
    # Adapter FASTA files the Debian package installs alongside the binaries.
    trimmomatic_adapters_dir: str = "/usr/share/trimmomatic"
    bwa_mem2_path: str = "bwa-mem2"
    minimap2_path: str = "minimap2"
    bowtie2_path: str = "bowtie2"
    # The index builders are separate binaries rather than subcommands, so
    # they need their own paths -- `bowtie2 index` is not a thing.
    bowtie2_build_path: str = "bowtie2-build"
    hisat2_path: str = "hisat2"
    hisat2_build_path: str = "hisat2-build"
    # STAR builds its own index through --runMode genomeGenerate, so unlike
    # bowtie2 and hisat2 it needs no second path here.
    star_path: str = "STAR"
    samtools_path: str = "samtools"
    fasterq_dump_path: str = "fasterq-dump"
    prefetch_path: str = "prefetch"
    nanoplot_path: str = "NanoPlot"
    # The NCBI Datasets CLI: how assemblies (GCA/GCF) are downloaded, as
    # fasterq-dump is how runs are. Installed in the worker image by the
    # Dockerfile; overridable for a host that has it elsewhere.
    datasets_path: str = "datasets"
    # bcftools does the short-read calling and all VCF indexing
    # (`bcftools index -t`), so it is the only new binary the code invokes for
    # variant calling besides Clair3 itself.
    bcftools_path: str = "bcftools"
    clair3_path: str = "run_clair3.sh"
    # From the `tabix` package. Compresses FASTQ/FASTA/VCF at ingest -- see
    # docs/superpowers/specs/2026-08-05-object-compression-design.md. Not a
    # user-selectable pipeline step, so it has no PipelineType card; the
    # storage layer dispatches to it directly and falls back to Python's
    # stdlib gzip when it is absent.
    bgzip_path: str = "bgzip"
    # From the `subread` package. featureCounts is the only binary in it this
    # application invokes.
    featurecounts_path: str = "featureCounts"
    # The de novo assembler, for long reads only. Debian ships it depending on
    # minimap2 and samtools, both of which this image already carries, so it
    # costs ~37MB rather than a toolchain.
    flye_path: str = "flye"
    # Bacterial genome annotation. On-demand delivery — the database is
    # several GB — so this probe only checks the binary, not the DB.
    bakta_path: str = "bakta"
    # Assembly completeness. Built from source in the Dockerfile -- neither is
    # packaged for trixie -- so compleasm resolves miniprot on PATH under this
    # exact name rather than needing a second setting passed through to it.
    compleasm_path: str = "compleasm"
    miniprot_path: str = "miniprot"
    # Amplicon/viral primer trimming and consensus calling. A Debian trixie
    # package (verified 2026-08-05: apt-cache policy ivar -> 1.4.4+dfsg-1,
    # after apt-get update -- checking without it always reports no
    # candidate regardless of what the repo actually carries).
    ivar_path: str = "ivar"
    # Short-read polishing of long-read assemblies. Not in Debian; installed
    # from upstream's musl-static release binary, and absent on arm64 by
    # design -- see backend/scripts/install-polypolish.sh.
    polypolish_path: str = "polypolish"
    # Reference-guided scaffolding. Not in Debian; installed from PyPI (pure
    # Python, pinned in backend/Dockerfile). The binary is `ragtag.py`, not
    # `ragtag` -- see tools.ragtag()'s own comment.
    ragtag_path: str = "ragtag.py"
    # Reference-based misassembly QC. Not in Debian; installed from the
    # GitHub release tarball, patched and trimmed -- see
    # backend/scripts/install-quast.sh. `quast_path` names a wrapper script,
    # not the tool's own quast.py, so the entry point on PATH is stable
    # regardless of where the tarball unpacks.
    quast_path: str = "quast.py"
    # /usr/local/bin/craq, a wrapper installed by
    # backend/scripts/install-craq.sh that execs the real Perl entrypoint
    # at its install location -- bin/craq resolves its src/ siblings
    # relative to its own path, so it cannot be symlinked.
    craq_path: str = "craq"
    # An absolute path, not a bare name, and deliberately so: Debian ships a
    # `meryl` package that is the Celera Assembler k-mer suite, a different
    # program with the same name. A bare PATH lookup would let a future
    # transitive `apt-get install meryl` shadow the correct binary with one
    # that reports a version, passes a naive probe, and fails at runtime.
    # See tools.meryl(), which also rejects that version string explicitly.
    meryl_path: str = "/opt/meryl/bin/meryl"
    # A wrapper script installed by backend/scripts/install-merqury.sh at
    # /usr/local/bin/merqury that sets $MERQURY and execs merqury.sh --
    # merqury.sh resolves its own siblings through that variable and cannot
    # simply be symlinked onto PATH.
    merqury_path: str = "merqury"
    # A pure-Python tool with no compiled binary; installed by
    # backend/scripts/install-gci.sh as a wrapper at /usr/local/bin/gci that
    # execs /opt/gci/GCI.py -- see that script for why it is a wrapper
    # rather than a symlink.
    gci_path: str = "gci"
    # Built from source by backend/scripts/install-winnowmap.sh -- Winnowmap
    # ships no binary releases. See that script for the two arm64 build
    # gotchas (the top-level Makefile's `-e` discarding the aarch64
    # `-fsigned-char` flag, and the bundled ext/meryl that must not be built).
    winnowmap_path: str = "winnowmap"
    # Model directories, one per Clair3 --platform. The install script
    # normalizes each to hold the checkpoint files directly.
    clair3_models_dir: str = "/opt/clair3/models"

    # The *host* path that BIOINFO_HOME is mounted from, for starting sibling
    # containers. Distinct from BIOINFO_HOME, which is already overloaded: the
    # compose file uses it as the host path in the bind mount and sets it to
    # /data inside the container. A sibling container gets its mounts from the
    # host, so it needs this value and not the container's own view.
    # Empty when unset, which host_path_for reports as a fixable error.
    bioinfo_home_host: str = ""

    # Architecture-dependent; see default_deepvariant_image above. Override with
    # DEEPVARIANT_IMAGE to pin a different build.
    deepvariant_image: str = Field(default_factory=default_deepvariant_image)

    # Threads a single trim run may use. Deliberately well below the core count:
    # the queue admits more than one compute job at a time, and fastp's own
    # scaling flattens out past a handful of threads while the IO cost does not.
    pipeline_default_threads: int = 4

    # Memory per samtools sort thread. samtools spills to disk when it runs out,
    # and its own default (768M) is conservative enough to make a large sort
    # thrash on a machine that had memory to spare.
    samtools_sort_mem_mb: int = 1024

    # Captured job output is the only record of how a run actually went, but it
    # is not worth keeping forever on a drive holding sequencing data.
    pipeline_log_retention_days: int = 30

    # --- AI summaries ---
    # The master switch. Off means no AI feature runs, whatever is configured
    # in the settings page.
    llm_summaries_enabled: bool = True
    # Generous: a small local model on CPU is not fast, and the alternative to
    # waiting is a summary that never appears.
    llm_timeout_seconds: float = 120.0
    # The model-list probe decides *whether* to bother, so it must be quick --
    # a slow "is it up" check would cost more than it saves.
    llm_health_timeout_seconds: float = 3.0
    # A few sentences, with headroom. Small models overshoot a length request,
    # and a summary cut off mid-sentence reads worse than a slightly long one.
    llm_max_tokens: int = 400

    # --- AI agent (in-app Pi harness) ---
    # Path to the pi CLI binary. The api image installs it (and its
    # pi-mcp-adapter extension) at build time -- see backend/Dockerfile.
    pi_path: str = "/usr/bin/pi"
    # Master switch. Off hides the agent UI entirely, whatever else is set.
    pi_disabled: bool = False
    # A prompt that gets no response within this window is treated as a dead
    # agent: the process is killed and the SSE stream delivers an error event.
    agent_response_timeout: int = 300
    # An idle agent process (no prompts, no streaming) is killed after this
    # long, releasing its memory. First slice is one conversation per project
    # with no persistence, so killing on idle loses nothing.
    agent_idle_timeout: int = 1800
    # Extra MCP servers merged into every agent's --mcp-config, e.g.
    # '{"ncbi": {"url": "https://...", "lifecycle": "lazy"}}' -- JSON from
    # the environment, validated by pydantic. See the agent spec's MCP config
    # builder for how the bioflow server entry itself is generated.
    agent_extra_mcp_servers: dict = Field(default_factory=dict)

    # Read once, at first startup after providers moved into the database, to
    # seed a provider from however this installation was already configured.
    # Nothing else reads these -- the base URL and model now live on the
    # provider document. See services/ai/migration.py.
    ai_legacy_base_url: str = Field(default="", alias="LLM_BASE_URL")
    ai_legacy_model: str = Field(default="", alias="LLM_MODEL")

    # --- Feedback notifications ---
    # When true, new feedback submissions are pushed to feedback_webhook_url
    # (a Discord-compatible webhook) after the database insert succeeds.
    # Delivery is best-effort: a failure is logged but never affects the
    # 201 response or the persisted record.
    feedback_enabled: bool = True
    feedback_webhook_url: str = ""

    log_level: str = "INFO"
    owner: str = "local"

    @property
    def register_roots(self) -> list[Path]:
        return [Path(p).resolve() for p in self.bioinfo_register_roots.split(":") if p]

    # Directory layout under BIOINFO_HOME.
    @property
    def objects_dir(self) -> Path:
        return self.bioinfo_home / "objects"

    @property
    def staging_dir(self) -> Path:
        return self.bioinfo_home / "staging"

    @property
    def tmp_dir(self) -> Path:
        return self.bioinfo_home / "tmp"

    @property
    def logs_dir(self) -> Path:
        return self.bioinfo_home / "logs"

    @property
    def agent_sessions_dir(self) -> Path:
        """Where pi keeps the agent's per-(profile, project) session files.

        Derived from BIOINFO_HOME so it follows a relocated home, and
        deliberately not under tmp/: unlike ncbi_dir, these files are the
        conversation itself, not a rebuildable cache.
        """
        return self.bioinfo_home / "agent-sessions"

    @property
    def ncbi_dir(self) -> Path:
        """Where the SRA Toolkit keeps its configuration and its cache.

        Set explicitly because the toolkit otherwise writes under $HOME, which
        in a container is whatever the runtime user happens to have -- often
        unwritable, and the resulting failure ("cannot open configuration")
        looks nothing like its cause. Derived from BIOINFO_HOME rather than
        hardcoded to /data so it follows a relocated home, and kept under tmp/
        because everything in it is a cache that can be rebuilt.
        """
        return self.tmp_dir / "ncbi"

    @property
    def ncbi_settings_path(self) -> Path:
        """The file `NCBI_SETTINGS` points at. See `ncbi_dir`."""
        return self.ncbi_dir / "user-settings.mkfg"

    @property
    def qc_reports_dir(self) -> Path:
        """Generated QC reports, keyed by object id.

        Outside objects/ deliberately: a FastQC report is derivative and
        regenerable, so content-addressing it would buy deduplication of
        something that is never shared and cost a blob record per run.
        """
        return self.bioinfo_home / "qc_reports"

    @property
    def bam_stats_dir(self) -> Path:
        """Generated BAM Results reports (the full per-contig TSV), keyed by
        object id.

        Outside objects/ deliberately, same rationale as qc_reports_dir: this
        is derivative and regenerable from the BAM itself, so content-
        addressing it would buy deduplication of something never shared and
        cost a blob record per run.
        """
        return self.bioinfo_home / "bam_stats"

    @property
    def vcf_stats_dir(self) -> Path:
        """Generated Variant Results artifacts (the variants TSV and the
        SQLite database the table queries), keyed by object id.

        Outside objects/ deliberately, same rationale as bam_stats_dir: both
        are derivative and regenerable from the VCF itself, so content-
        addressing them would buy deduplication of something never shared and
        cost a blob record per run.
        """
        return self.bioinfo_home / "vcf_stats"

    @property
    def annotation_stats_dir(self) -> Path:
        """Generated Annotation Results artifacts (the SQLite feature table),
        keyed by object id.

        Outside objects/ deliberately, same rationale as vcf_stats_dir: this
        is derivative and regenerable from the annotation file itself, so
        content-addressing it would buy deduplication of something never
        shared and cost a blob record per run.
        """
        return self.bioinfo_home / "annotation_stats"

    @property
    def lineages_dir(self) -> Path:
        """compleasm's `--library_path`: downloaded lineage datasets, shared
        across every project and every run.

        Reference data, not a per-object artifact -- closer to `ncbi_dir`'s
        cache than to `objects/`, and for the same underlying reason
        `download_lineage` is its own job rather than something
        `assess_completeness` fetches inline: a completeness job must not
        depend on the network, so what it reads here must already exist.
        """
        return self.bioinfo_home / "lineages"

    @property
    def meta_dir(self) -> Path:
        return self.bioinfo_home / ".biopipe"

    @property
    def sentinel_path(self) -> Path:
        """Proves the drive is actually mounted. See storage/home.py."""
        return self.meta_dir / "VERSION"

    @property
    def lock_path(self) -> Path:
        return self.meta_dir / "lock"

    @property
    def is_compute_node(self) -> bool:
        return self.node_type == "compute"


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
